# Generated by Django 5.2.6 on 2025-09-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="competence_level",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="core.competencelevel",
                verbose_name="Имеющиеся уровни компетенций",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="missions",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="core.mission",
                verbose_name="Пройденные миссии",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.PositiveIntegerField(default=1, verbose_name="Ранг"),
        ),
    ]
