# Generated by Django 5.2.6 on 2025-09-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_prize"),
        ("users", "0002_user_competence_level_user_missions_user_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="experience",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Опыт"),
        ),
        migrations.AddField(
            model_name="user",
            name="prices",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="core.prize",
                verbose_name="Полученные призы",
            ),
        ),
    ]
