# Generated by Django 5.2.6 on 2025-09-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_balance_user_experience_user_prices"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="prices",
            new_name="prizes",
        ),
    ]
