# Generated by Django 5.2.6 on 2025-09-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_prices_user_prizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="balance",
        ),
    ]
