# Generated by Django 5.2.6 on 2025-09-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(default="light", max_length=10, verbose_name="Тема"),
        ),
    ]
