# Generated by Django 5.2.6 on 2025-09-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="experience",
            field=models.PositiveIntegerField(default=0, verbose_name="Опыт"),
        ),
        migrations.AlterField(
            model_name="user",
            name="mana",
            field=models.PositiveIntegerField(default=0, verbose_name="Мана"),
        ),
    ]
