# Generated by Django 5.2.6 on 2025-09-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_experience_alter_user_mana"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invite_users",
            field=models.PositiveIntegerField(default=0, verbose_name="Число приглашённых пользователей"),
        ),
    ]
