# Generated by Django 5.2.6 on 2025-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_invite_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_hr",
            field=models.BooleanField(default=False, verbose_name="HR"),
        ),
    ]
