# Generated by Django 5.2.6 on 2025-09-26 12:42

from django.db import migrations

from users.models import User


def forwards_func(apps, schema_editor):  # noqa
    user = User.objects.create_superuser("hr", "hr@alabuga.ru", "iR98ixXr")
    user.is_hr = True
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_is_hr"),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=migrations.RunPython.noop),
    ]
