# Generated by Django 5.2.6 on 2025-09-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_is_hr"),
    ]

    operations = []
