# Generated by Django 5.2.6 on 2025-09-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20250926_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_organizer",
            field=models.BooleanField(default=False, verbose_name="Организатор"),
        ),
    ]
