# Generated by Django 5.2.6 on 2025-09-27 22:42

from django.db import migrations, models

from users.models import User


def forwards_func(apps, schema_editor):  # noqa
    user = User.objects.create_superuser("hr", "hr@alabuga.ru", "iR98ixXr")
    user.is_hr = True
    user.save()

    for name in ["org1", "org2", "org3", "org4"]:
        user = User.objects.create_user(name, f"{name}@alabuga.ru", "iR98ixXr")
        user.is_organizer = True
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20250926_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_organizer",
            field=models.BooleanField(default=False, verbose_name="Организатор"),
        ),
        migrations.RunPython(code=forwards_func, reverse_code=migrations.RunPython.noop),
    ]
