# Generated by Django 5.2.6 on 2025-09-18 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компетенция",
                "verbose_name_plural": "Компетенции",
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Миссия",
                "verbose_name_plural": "Миссии",
            },
        ),
        migrations.CreateModel(
            name="CompetenceLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(verbose_name="Уровень")),
                (
                    "competence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="core.competence",
                        verbose_name="Компетенция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уровень компетенции",
                "verbose_name_plural": "Уровни компетенций",
            },
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name="Уровень"),
                ),
                ("name", models.TextField(verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                (
                    "experience",
                    models.PositiveIntegerField(verbose_name="Требуемый опыт"),
                ),
                (
                    "competence_level",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ranks",
                        to="core.competencelevel",
                        verbose_name="Требуемые уровни компетенций",
                    ),
                ),
                (
                    "missions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ranks",
                        to="core.mission",
                        verbose_name="Требуемые миссии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ранг",
                "verbose_name_plural": "Ранги",
                "ordering": ["id"],
            },
        ),
    ]
