# Generated by Django 5.2.6 on 2025-09-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_rank_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="competence",
            name="description",
            field=models.TextField(default="", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competence",
            name="image",
            field=models.ImageField(default="", upload_to="", verbose_name="Изображение"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="competence",
            name="name",
            field=models.CharField(default="", max_length=1024, verbose_name="Название"),
            preserve_default=False,
        ),
    ]
