# Generated by Django 5.2.6 on 2025-09-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_competence_description_competence_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competence",
            options={
                "ordering": ["id"],
                "verbose_name": "Компетенция",
                "verbose_name_plural": "Компетенции",
            },
        ),
    ]
