# Generated by Django 5.2.6 on 2025-09-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_competence_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="", verbose_name="Изображение")),
                ("cost", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "is_salable",
                    models.BooleanField(default=True, verbose_name="Доступен для продажи?"),
                ),
                (
                    "need_hr_notif",
                    models.BooleanField(
                        default=False,
                        verbose_name="Необходимо уведомить HR о получении",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приз",
                "verbose_name_plural": "Призы",
                "ordering": ["-id"],
            },
        ),
    ]
