# Generated by Django 5.2.6 on 2025-09-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_prize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prize",
            name="name",
            field=models.CharField(max_length=1024, verbose_name="Название"),
        ),
    ]
