# Generated by Django 5.2.6 on 2025-09-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_prize_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mission",
            options={
                "ordering": ["id"],
                "verbose_name": "Миссия",
                "verbose_name_plural": "Миссии",
            },
        ),
        migrations.AddField(
            model_name="mission",
            name="child_missions",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_missions",
                to="core.mission",
                verbose_name="Дочерние миссии",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="competence_level",
            field=models.ManyToManyField(
                blank=True,
                related_name="missions",
                to="core.competencelevel",
                verbose_name="Даёт компетенции",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="description",
            field=models.TextField(default="", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mission",
            name="experience",
            field=models.PositiveIntegerField(default=0, verbose_name="Опыт"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mission",
            name="image",
            field=models.ImageField(default="", upload_to="", verbose_name="Изображение"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mission",
            name="mana",
            field=models.PositiveIntegerField(default=1, verbose_name="Мана"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mission",
            name="min_rank",
            field=models.PositiveIntegerField(default=1, verbose_name="Ранг"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mission",
            name="name",
            field=models.CharField(default="", max_length=1024, verbose_name="Название"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mission",
            name="prizes",
            field=models.ManyToManyField(
                blank=True,
                related_name="missions",
                to="core.prize",
                verbose_name="Дает призы",
            ),
        ),
    ]
