# Generated by Django 5.2.6 on 2025-09-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_mission_options_mission_child_missions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="child_missions",
        ),
        migrations.CreateModel(
            name="MissionTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_child",
                        to="core.mission",
                        verbose_name="Дочерняя миссия",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="as_parent",
                        to="core.mission",
                        verbose_name="Корневая миссия",
                    ),
                ),
            ],
        ),
    ]
