# Generated by Django 5.2.6 on 2025-09-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_mission_child_missions_missiontree"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="min_rank",
        ),
        migrations.AddField(
            model_name="mission",
            name="rank",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rank_missions",
                related_query_name="Ранг",
                to="core.rank",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rank",
            name="missions",
            field=models.ManyToManyField(
                blank=True,
                related_name="ranks_where_required",
                to="core.mission",
                verbose_name="Требуемые миссии",
            ),
        ),
    ]
