# Generated by Django 5.2.6 on 2025-09-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_mission_min_rank_mission_rank_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rank_missions",
                to="core.rank",
                verbose_name="Ранг",
            ),
        ),
    ]
