# Generated by Django 5.2.6 on 2025-09-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_mission_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="prize",
            name="rare",
            field=models.PositiveIntegerField(default=1, verbose_name="Редкость"),
            preserve_default=False,
        ),
    ]
