# Generated by Django 5.2.6 on 2025-09-19 23:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0011_prize_rare"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionCode",
            fields=[
                (
                    "mission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.mission",
                    ),
                ),
                ("code", models.CharField(max_length=1024, verbose_name="Код")),
            ],
            options={
                "verbose_name": "Миссия Квест",
                "verbose_name_plural": "Миссии Квест",
                "ordering": ["id"],
            },
            bases=("core.mission",),
        ),
        migrations.CreateModel(
            name="MissionRecruiting",
            fields=[
                (
                    "mission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.mission",
                    ),
                ),
                (
                    "invited",
                    models.PositiveIntegerField(verbose_name="Сколько необходимо пригласить"),
                ),
            ],
            options={
                "verbose_name": "Миссия Рекрутинг",
                "verbose_name_plural": "Миссии Рекрутинг",
                "ordering": ["id"],
            },
            bases=("core.mission",),
        ),
        migrations.CreateModel(
            name="MissionTeaching",
            fields=[
                (
                    "mission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.mission",
                    ),
                ),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                "verbose_name": "Миссия Лекторий",
                "verbose_name_plural": "Миссии Лекторий",
                "ordering": ["id"],
            },
            bases=("core.mission",),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="mission",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="rank",
            field=models.IntegerField(verbose_name="Ранг"),
        ),
        migrations.CreateModel(
            name="MissionQuiz",
            fields=[
                (
                    "mission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.mission",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="missions",
                        to="core.question",
                        verbose_name="Вопросы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Миссия Симулятор",
                "verbose_name_plural": "Миссии Симулятор",
                "ordering": ["id"],
            },
            bases=("core.mission",),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                (
                    "question",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.question"),
                ),
            ],
        ),
    ]
