# Generated by Django 5.2.6 on 2025-09-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_missioncode_missionrecruiting_missionteaching_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="file",
            field=models.FileField(default="", upload_to=""),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="QuestionMedia",
        ),
    ]
