# Generated by Django 5.2.6 on 2025-09-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_question_file_delete_questionmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["id"],
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["id"],
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
    ]
