# Generated by Django 5.2.6 on 2025-09-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_answer_options_alter_question_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prize",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="prize",
            name="is_salable",
        ),
        migrations.RemoveField(
            model_name="question",
            name="text",
        ),
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.TextField(default="", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="name",
            field=models.CharField(default="", max_length=1024, verbose_name="Название"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="missioncode",
            name="code",
            field=models.CharField(max_length=1024, unique=True, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="question",
            name="file",
            field=models.FileField(upload_to="", verbose_name="Файл"),
        ),
    ]
