# Generated by Django 5.2.6 on 2025-09-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_prize_cost_remove_prize_is_salable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="", verbose_name="Файл"),
        ),
    ]
