# Generated by Django 5.2.6 on 2025-09-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_question_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="prize",
            name="is_buying",
            field=models.BooleanField(default=False, verbose_name="Можно купить в магазине"),
        ),
        migrations.AddField(
            model_name="prize",
            name="price",
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Цена"),
        ),
    ]
