# Generated by Django 5.2.6 on 2025-09-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_prize_is_buying_prize_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competence",
            name="image",
        ),
        migrations.AlterField(
            model_name="mission",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="rank",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Аватар пользователя"),
        ),
    ]
