# Generated by Django 5.2.6 on 2025-09-26 12:39

from django.db import migrations, models

from core.models import Competence


def forwards_func(apps, schema_editor):  # noqa
    Competence.objects.bulk_create(
        [
            Competence(name=name)
            for name in [
                "Вера в дело",
                "Стремление к большему",
                "Общение",
                "Аналитика",
                "Командование",
                "Юриспруденция",
                "Трёхмерное мышление",
                "Базовая экономика",
                "Основы аэронавигации",
            ]
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_competence_image_alter_mission_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competence",
            name="description",
        ),
        migrations.AlterField(
            model_name="prize",
            name="rare",
            field=models.PositiveIntegerField(default=0, verbose_name="Редкость"),
        ),
        migrations.RunPython(code=forwards_func, reverse_code=migrations.RunPython.noop),
    ]
