# Generated by Django 5.2.6 on 2025-09-27 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_competence_description_alter_prize_rare"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missioncode",
            options={
                "ordering": ["id"],
                "verbose_name": "Миссия Исследование",
                "verbose_name_plural": "Миссии Исследование",
            },
        ),
        migrations.CreateModel(
            name="MissionManual",
            fields=[
                (
                    "mission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.mission",
                    ),
                ),
                (
                    "organizers",
                    models.ManyToManyField(
                        related_name="missions_as_org",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Организаторы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Миссия Квест",
                "verbose_name_plural": "Миссии Квест",
                "ordering": ["id"],
            },
            bases=("core.mission",),
        ),
    ]
