# Generated by Django 5.2.6 on 2025-09-27 23:15

from django.db import migrations

from users.models import User


def forwards_func(apps, schema_editor):  # noqa
    for name in ["org1", "org2", "org3", "org4"]:
        user = User.objects.create_superuser(name, f"{name}@alabuga.ru", "password")
        user.is_organizer = True
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_missioncode_options_missionmanual"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competencelevel",
            options={
                "ordering": ["id"],
                "verbose_name": "Уровень компетенции",
                "verbose_name_plural": "Уровни компетенций",
            },
        ),
        migrations.RunPython(code=forwards_func, reverse_code=migrations.RunPython.noop),
    ]
