# Generated by Django 5.2.6 on 2025-09-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_missioncode_options_missionmanual"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competencelevel",
            options={
                "ordering": ["id"],
                "verbose_name": "Уровень компетенции",
                "verbose_name_plural": "Уровни компетенций",
            },
        ),
    ]
