# Generated by Django 5.2.6 on 2025-09-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_competencelevel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="missions",
            field=models.ManyToManyField(
                blank=True,
                related_name="ranks_where_required",
                to="core.mission",
                verbose_name="Обязательные миссии",
            ),
        ),
    ]
